#define SECTOR_SIZE 4096
#define PAGE_SIZE (SECTOR_SIZE * 64) // 256K
#define DB_HEADER_FLAGS_SIZE 1
#define DB_HEADER_MAX_ROOTS_SIZE 75000
#define DB_HEADER_TABLE_COUNTER_SIZE 1
#define DB_HEADER_FIRST_FREE_BYTE_SIZE 8
#define ROOT_NAME_MAX_SIZE 255
#define ROOT_NAME_SIZE 1
#define ROOT_POINTER_SIZE 4
#define DB_HEADER_SIZE (DB_HEADER_FLAGS_SIZE+DB_HEADER_MAX_ROOTS_SIZE+DB_HEADER_TABLE_COUNTER_SIZE+DB_HEADER_FIRST_FREE_BYTE_SIZE)
#define MAX_TABLES DB_HEADER_MAX_ROOTS_SIZE/(ROOT_NAME_MAX_SIZE+ROOT_NAME_SIZE+ROOT_POINTER_SIZE)

void pager_real_write(unsigned int id, const char* page);